services:
  newtarr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newtarr
    ports:
      - "9705:9705"
    volumes:
      - newtarr-config:/config
    environment:
      - TZ=America/New_York
    restart: unless-stopped

volumes:
  newtarr-config:
    name: newtarr-config